### ISSUE TITLE
CoreMiner not working on raspberry Pi

### ISSUE THREAD

**Issue by simanuel** [catchthatrabbit/coreminer#21]
On my raspberry pi, after setting up the coreminer, I'm getting an error:
● Mine settings file 'pool.cfg' exists.
● Importing settings.
● Wallet validated.
● Configuring stratum server.
● Starting mining command.
./mine.sh: Zeile 97: ./coreminer: Kann die Binärdatei nicht ausführen: Fehler im Format der Programmdatei
(Cannot run the binary: error in program file format).

**Comment by raisty** [comment]
Please, send us the hardware specification, so that we can test it.

**Comment by simanuel** [comment]
Raspberry Pi 4 (4GB), Raspbian GNU/Linux 10 (buster) and
Raspberry Pi 3, Raspbian GNU/Linux 7 (wheezy)
The error on the raspberry 3 is:
./mine.sh: Zeile 97: ./coreminer: Kann die Datei nicht ausführen.
(Cannot run the file.)

**Comment by raisty** [comment]
Thank you. We will test it.

**Comment by raisty** [comment]
We are testing several OS on Raspberry foundation hardware.

**Comment by simanuel** [comment]
Okay, I checked my version of Libc and it is 2.28. 
Another OS is no option for me at the moment, so I hope it will be possible in the near future to use the coreminer with an older version of Libc.

**Comment by stylepatrick** [comment]
Hello,

i installed on my PI4 the latest Ubuntu 22.04 LTS with Libc 2.35 but getting the same issue:

`./mine.sh: line 97: ./coreminer: cannot execute binary file: Exec format error`

Any other options or am i doing something wrong?

**Comment by raisty** [comment]
Documentation was updated with the requirement of `GLIBC_2.33`.

**Comment by raisty** [comment]
> Hello,
> 
> i installed on my PI4 the latest Ubuntu 22.04 LTS with Libc 2.35 but getting the same issue:
> 
> `./mine.sh: line 97: ./coreminer: cannot execute binary file: Exec format error`
> 
> Any other options or am i doing something wrong?

Seems like not related to this topic, please feel free to raise another issue.

**Comment by gubowork** [comment]
Can U give instruction how to install GLIBC_2.33. ? 
https://www.screencast.com/t/FfG3YXjTd
![image](https://user-images.githubusercontent.com/5851673/168449157-323d859b-e5be-43c5-a371-6dd42869d32f.png)

**Comment by raisty** [comment]
I highly recommended upgrading OS if possible.

For further advice, feel free to open another issue with a description of your hardware and OS.

Thank you.

**Comment by stylepatrick** [comment]
> Hello,
> 
> 
> 
> i installed on my PI4 the latest Ubuntu 22.04 LTS with Libc 2.35 but getting the same issue:
> 
> 
> 
> `./mine.sh: line 97: ./coreminer: cannot execute binary file: Exec format error`
> 
> 
> 
> Any other options or am i doing something wrong?

I still have the same issue. Setting everything up from scratch with Ubuntu 22.04. Was someone able to get it running on Raspberry?

**Comment by Patrick010** [comment]
> Raspbian has difficulties because Raspbian OS is using Libc 2.31. Coreminer requires a minimum Libc 2.33.
> 
> But OS like:
> 
>     * [Ubuntu 20.04](https://ubuntu.com/download/alternative-downloads) or [newer](https://ubuntu.com/download/server/arm)
> 
>     * [Kali-ARM Raspberry Pi 2 (v1.2), 3, 4, and 400 (64-Bit)](https://www.kali.org/get-kali/#kali-arm)
> 
> 
> Are working.
> 
> As a quick fix, I recommended using another OS.
> 
> We will investigate if we can downgrade w/o losing hash rate.

Move from bullseye to testing in sources.list and do an update && upgrade && dist-upgrade. This will install libc 2.33 on your Pi.

**Comment by Crownvill** [comment]
> 

Hi stylepatrick,
I'm running coreminer on a raspberry pi 3 B+. OS is currently Manjaro ARM 22.04 (included in Raspberry Pi Imager). It's running quite well but I got the feeling that the hash-rat is lower on Manjaro than on Kali, which I tested a couple of days ago (Kali-ARM Raspberry Pi 2 (v1.2), 3, 4, and 400 (64-Bit)).

**Comment by Patrick010** [comment]
@Crownvill What rates do you get and what should be concidered 'normal'? I've got it running on a Pi 4B since last night and my last 30min hashrate is 637h/s

**Comment by Crownvill** [comment]
@Patrick010 as far as I remember, I got around 600 - 800h/s with Kali. Currently (running Manjaro) I got around 200h/s. I'll change back to Kali when I'll have time.

**Comment by Patrick010** [comment]
@Crownvill interesting having such a big difference in hashrates, being both Debian OS's

**Comment by stylepatrick** [comment]
> > 
> 
> Hi stylepatrick, I'm running coreminer on a raspberry pi 3 B+. OS is currently Manjaro ARM 22.04 (included in Raspberry Pi Imager). It's running quite well but I got the feeling that the hash-rat is lower on Manjaro than on Kali, which I tested a couple of days ago (Kali-ARM Raspberry Pi 2 (v1.2), 3, 4, and 400 (64-Bit)).

Thank you! I will try with Kali Linux today.

**Comment by Crownvill** [comment]
@Patrick010 yes - but of course also difficulty increased. I'll test again this evening.

**Comment by Crownvill** [comment]
> @Crownvill How does this difficulty thing work? tonight i'm gonna make 2 vm's, one with standard deb, one kali and compare them. Lets see what comes out

I think @raisty is the expert for this, but as far as I understood difficulty of hashes is increasing over time, the more coins got mined, right @raisty?

**Comment by Patrick010** [comment]
https://en.bitcoin.it/wiki/Difficulty

**Comment by stylepatrick** [comment]
> > > 
> > 
> > 
> > Hi stylepatrick, I'm running coreminer on a raspberry pi 3 B+. OS is currently Manjaro ARM 22.04 (included in Raspberry Pi Imager). It's running quite well but I got the feeling that the hash-rat is lower on Manjaro than on Kali, which I tested a couple of days ago (Kali-ARM Raspberry Pi 2 (v1.2), 3, 4, and 400 (64-Bit)).
> 
> Thank you! I will try with Kali Linux today.

I am still not able to mine. Tried with Ubuntu 22.04 and Kali Linux. This is the output:
![image](https://user-images.githubusercontent.com/52086629/168833756-d0359c24-1c68-47bc-96db-9c8fe6403628.png)

My PI is from 2018 could it be that the software is not compatible with armv7l? I dont have any other ideas to try.

**Comment by Patrick010** [comment]
Same here. Just installed a Debian Bookworm and Kali kali-rolling vm, both refuse to run coreminer;

Debian: -bash: ./coreminer: cannot execute binary file: Exec format error
Kali: zsh: exec format error: ./coreminer

**Comment by stylepatrick** [comment]
Got it fixed. armv7l is 32bit. Coreminer is compiled for arm64. Please take care that you install a 64bit OS, otherwise it will not work. 

With Ubuntu Server 22.04 i am getting ~350H/s. Does anyone has more Hash on PI4 4GB RAM?

**Comment by Patrick010** [comment]
All my installations are 64bit, so must be something else. Maybe @simanuel can enlighten us?

My Pi4 does around the same; ~350H/s

**Comment by raisty** [comment]
> > @Crownvill How does this difficulty thing work? tonight i'm gonna make 2 vm's, one with standard deb, one kali and compare them. Lets see what comes out
> 
> I think @raisty is the expert for this, but as far as I understood difficulty of hashes is increasing over time, the more coins got mined, right @raisty?

Right, the difficulty is calculated by the formula. Some of the variables are the amount (and strength) of machines in the network.

**Comment by raisty** [comment]
Two things to check:

- version of Glibc
- miner release matching for your CPU architecture
