### ISSUE TITLE
[BUG] coreminer does not run on Synology DSM 7.1

### ISSUE THREAD

**Issue by Patrick010** [catchthatrabbit/coreminer#33]
### Device

Synology DS920+

### CPU Architecture

x86-64

### CPU brand

Intel

### CPU model

Celeron J4125 4-core 2.0 GHz

### OS and version

DSM 7.1-42661 Update 1

### Software version

coreminer v0.19.60

### Bug

coreminer does not run

### Reproduce Bug

run mine.sh
enter required fields for .cfg generation
start mining
mine.sh: line 97: ./coreminer: cannot execute binary file: Exec format error

### Expected behavior

coreminer starts mining

**Comment by raisty** [comment]
Please, check two things:

1. You have the correct version of the miner for your environment.
2. Please, send us here version of your [glibc](https://www.gnu.org/software/libc/).

We will investigate more your case.

**Comment by raisty** [comment]
This Issue is stale, please consider to reopen with more information.
