### ISSUE TITLE
[BUG] Error: The following arguments were not expected: 2 -t

### ISSUE THREAD

**Issue by mdndngns** [catchthatrabbit/coreminer#55]
### Device

RP pi 4

### CPU Architecture

arm64

### OS and version

debian

### Software version

coreminer 0.19.0+commit.8d3c1299

### Bug

Miner don't start with a Number of  Threads in the pool.cfg.

```
coreminer 0.19.0+commit.8d3c1299
Build: linux/release/gnu

Error: The following arguments were not expected: 2 -t
```

### Reproduce Bug

Start the miner without cfg file an follow the steps.

### Expected behavior

Only "threads=all" works.

**Comment by raisty** [comment]
Fixed with #56
