### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TobiW47** [catchthatrabbit/coreminer#71]
### Device

AMD Ryzen 9 3950x on Asus Prime 470-pro

### CPU Architecture

x86-64

### CPU brand

AMD

### CPU model

AMD Ryzen 9 3950x

### OS and version

Ubuntu 20.04 LTS

### Software version

0.19.72

### Bug

Hi there,

Can you perhaps help me with my hashing issue? I run ubuntu 20.04 LTS and my CPU is not producing any hashes.

Is there a way to debug the coreminer?

Kind regards

TobiW47

 / ___/__  _______ /  |/  (_)__  ___ ____
/ /__/ _ \/ __/ -_) /|_/ / / _ \/ -_) __/
\___/\___/_/  \__/_/  /_/_/_//_/\__/_/

● Mine settings file 'pool.cfg' exists.
● Importing settings.
● Wallet validated.
● Configuring stratum server.
● Starting mining command.

coreminer 0.19.0+commit.e927ce13
Build: linux/release/gnu

cp 07:36:45 main     RandomY large pages mode is enabled
cp 07:36:45 main     RandomY hard aes mode is enabled
cp 07:36:45 main     RandomY full mem mode is enabled
cp 07:36:45 main     RandomY JIT mode is enabled
 i 07:36:46 main     Configured pool [eu.catchthatrabbit.com:8008](http://eu.catchthatrabbit.com:8008/)
 i 07:36:46 main     Configured pool [eu1.catchthatrabbit.com:8008](http://eu1.catchthatrabbit.com:8008/)
 i 07:36:46 <unknown> Selected pool [eu.catchthatrabbit.com:8008](http://eu.catchthatrabbit.com:8008/)
 i 07:36:46 <unknown> Stratum mode : Eth-Proxy compatible
 i 07:36:46 <unknown> Established connection to [eu.catchthatrabbit.com](http://eu.catchthatrabbit.com/) [[168.119.96.215:8008](http://168.119.96.215:8008/)]
 i 07:36:46 <unknown> Spinning up miners...
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 0 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 1 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 10 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 11 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 12 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 13 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 2 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 3 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 4 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 5 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 6 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 7 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 8 Memory : 14.48 GB
cp 07:36:46 <unknown> RandomY large pages mode is enabled
cp 07:36:46 <unknown> RandomY hard aes mode is enabled
cp 07:36:46 <unknown> RandomY full mem mode is enabled
cp 07:36:46 <unknown> RandomY JIT mode is enabled
cp 07:36:46 <unknown> Using CPU: 9 Memory : 14.48 GB
 i 07:36:46 <unknown> Epoch : -1 Difficulty : 2.17 Mh
 i 07:36:46 <unknown> Job: ee1af8fc… [eu.catchthatrabbit.com](http://eu.catchthatrabbit.com/) [[168.119.96.215:8008](http://168.119.96.215:8008/)]
 i 07:36:50 <unknown> Epoch : -1 Difficulty : 2.17 Mh
 i 07:36:50 <unknown> Job: 31d14e2d… [eu.catchthatrabbit.com](http://eu.catchthatrabbit.com/) [[168.119.96.215:8008](http://168.119.96.215:8008/)]
 m 07:36:51 <unknown> 0:00 A0 0.00 h - cp0 0.00, cp1 0.00, cp2 0.00, cp3 0.00, cp4 0.00, cp5 0.00, cp6 0.00, cp7 0.00, cp8 0.00, cp9 0.00, cp10 0.00, cp11 0.00, cp12 0.00, cp13 0.00
 i 07:36:53 <unknown> Epoch : -1 Difficulty : 2.17 Mh
 i 07:36:53 <unknown> Job: b04541ac… [eu.catchthatrabbit.com](http://eu.catchthatrabbit.com/) [[168.119.96.215:8008](http://168.119.96.215:8008/)]
 m 07:36:56 <unknown> 0:00 A0 0.00 h - cp0 0.00, cp1 0.00, cp2 0.00, cp3 0.00, cp4 0.00, cp5 0.00, cp6 0.00, cp7 0.00, cp8 0.00, cp9 0.00, cp10 0.00, cp11 0.00, cp12 0.00, cp13 0.00
 i 07:36:59 <unknown> Epoch : -1 Difficulty : 2.17 Mh
 i 07:36:59 <unknown> Job: 0f4f85ba… [eu.catchthatrabbit.com](http://eu.catchthatrabbit.com/) [[168.119.96.215:8008](http://168.119.96.215:8008/)]
 m 07:37:01 <unknown> 0:00 A0 0.00 h - cp0 0.00, cp1 0.00, cp2 0.00, cp3 0.00, cp4 0.00, cp5 0.00, cp6 0.00, cp7 0.00, cp8 0.00, cp9 0.00, cp10 0.00, cp11 0.00, cp12 0.00, cp13 0.00
 i 07:37:01 <unknown> Epoch : -1 Difficulty : 2.17 Mh
 i 07:37:01 <unknown> Job: 118068eb… [eu.catchthatrabbit.com](http://eu.catchthatrabbit.com/) [[168.119.96.215:8008](http://168.119.96.215:8008/)]
 i 07:37:05 <unknown> Epoch : -1 Difficulty : 2.17 Mh
 i 07:37:05 <unknown> Job: 9e3bc30a… [eu.catchthatrabbit.com](http://eu.catchthatrabbit.com/) [[168.119.96.215:8008](http://168.119.96.215:8008/)]
 m 07:37:06 <unknown> 0:00 A0 0.00 h - cp0 0.00, cp1 0.00, cp2 0.00, cp3 0.00, cp4 0.00, cp5 0.00, cp6 0.00, cp7 0.00, cp8 0.00, cp9 0.00, cp10 0.00, cp11 0.00, cp12 0.00, cp13 0.00
 m 07:37:11 <unknown> 0:00 A0 0.00 h - cp0 0.00, cp1 0.00, cp2 0.00, cp3 0.00, cp4 0.00, cp5 0.00, cp6 0.00, cp7 0.00, cp8 0.00, cp9 0.00, cp10 0.00, cp11 0.00, cp12 0.00, cp13 0.00
 m 07:37:16 <unknown> 0:00 A0 0.00 h - cp0 0.00, cp1 0.00, cp2 0.00, cp3 0.00, cp4 0.00, cp5 0.00, cp6 0.00, cp7 0.00, cp8 0.00, cp9 0.00, cp10 0.00, cp11 0.00, cp12 0.00, cp13 0.00
^C i 07:37:16 main     Got interrupt ...
 i 07:37:16 main     Disconnected from [eu.catchthatrabbit.com](http://eu.catchthatrabbit.com/) [[168.119.96.215:8008](http://168.119.96.215:8008/)]
 i 07:37:16 main     Shutting down miners...
 i 07:37:16 main     Terminated!

### Reproduce Bug

Install coreminer on Simple Mining OS, which is Ubuntu 20.04 LTS

Start coreminer

Result: Zero hashrate

### Expected behavior

Starts hashing with 18.x KH/sec

**Comment by rastislavcore** [comment]
To debug the bash script you can use [Bash xtrace](https://linuxconfig.org/how-to-debug-bash-scripts).

This will provide you with more information about the bash script itself.

In case you are looking for all the commands, please use: `coreminer --help`

If you want to see more functionality or changes in the code, please raise the [feature request](https://github.com/catchthatrabbit/coreminer/issues/new?assignees=raisty&labels=feature&template=feature_request.yml&title=%5BFEATURE%5D+).

To classify this as a bug, you need to provide more information. Please, feel free to reopen this issue with more information.

**Comment by TobiW47** [comment]
With the latest coreminer version the issue still persists. Ubuntu 20.04.1 LTS supports max glibc 2.31.

Can the coreminer app be re-compiled or made compatible?
