### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AFP99** [catchthatrabbit/coreminer#92]
### Device

coreminer

### CPU Architecture

x86-64

### CPU brand

all CPU

### CPU model

all model

### OS and version

Ubuntu 22.04LTS

### Software version

latest

### Bug

In ibpoolprotocols/getwork/XcbGetworkClient.cpp Row  28 instead of  eth_getWork it should be  xcb_getWork, otherwise mining to local node will not work.

 X 18:01:33 <unknown> Got code:-32601 message:the method eth_getWork does not exist/is not available  from localhost:8545

### Reproduce Bug

./coreminer -t 1 -P getwork://cbxxxx.....@localhost:8545 .

### Expected behavior

It should mine against the local node

**Comment by rastislavcore** [comment]
Resolved with #99
