### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by Adariles-Cardi** [catchthatrabbit/coreminer#93]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

_Originally posted by @rastislavcore in https://github.com/catchthatrabbit/coreminer/discussions/25_

**Comment by Adariles-Cardi** [comment]
Hello , I am interested in running a node but it's my first. I have an older Mac pro tower with xeon e5 2610 dual 2.4 gtz &  12 ram but I have SATA drive is that ok?! I have Ubuntu 22.04 lts installed which go core client I need? 

Is the a short video on this tutorial? 

I got this as I tried last night
![IMG_20240214_191116942](https://github.com/catchthatrabbit/coreminer/assets/92275638/843bc9ee-71a3-428b-8bd0-986321a73fee)

**Comment by rastislavcore** [comment]
Thank you for the note, please open go-core related issues in: https://github.com/core-coin/go-core/issues
Please, attach more details about your environment as well.
If you are seeking discussion board, you can join Discord and open forum question. https://discord.com/channels/469227792538533888/1285602978836774953
